development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qm_development
  pool: 5
  username: qm
  password: qm=MqmOM
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qm_test
  pool: 5
  username: qm
  password: qm=MqmOM
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: qm_production
  pool: 5
  username: qm
  password: qm=MqmOM
  host: localhost
