require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstructionDocumentAssignmentsController do

  # This should return the minimal set of attributes required to create a valid
  # InstructionDocumentAssignment. As you add validations to InstructionDocumentAssignment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "instruction_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InstructionDocumentAssignmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all instruction_document_assignments as @instruction_document_assignments" do
      instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:instruction_document_assignments).should eq([instruction_document_assignment])
    end
  end

  describe "GET show" do
    it "assigns the requested instruction_document_assignment as @instruction_document_assignment" do
      instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
      get :show, {:id => instruction_document_assignment.to_param}, valid_session
      assigns(:instruction_document_assignment).should eq(instruction_document_assignment)
    end
  end

  describe "GET new" do
    it "assigns a new instruction_document_assignment as @instruction_document_assignment" do
      get :new, {}, valid_session
      assigns(:instruction_document_assignment).should be_a_new(InstructionDocumentAssignment)
    end
  end

  describe "GET edit" do
    it "assigns the requested instruction_document_assignment as @instruction_document_assignment" do
      instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
      get :edit, {:id => instruction_document_assignment.to_param}, valid_session
      assigns(:instruction_document_assignment).should eq(instruction_document_assignment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstructionDocumentAssignment" do
        expect {
          post :create, {:instruction_document_assignment => valid_attributes}, valid_session
        }.to change(InstructionDocumentAssignment, :count).by(1)
      end

      it "assigns a newly created instruction_document_assignment as @instruction_document_assignment" do
        post :create, {:instruction_document_assignment => valid_attributes}, valid_session
        assigns(:instruction_document_assignment).should be_a(InstructionDocumentAssignment)
        assigns(:instruction_document_assignment).should be_persisted
      end

      it "redirects to the created instruction_document_assignment" do
        post :create, {:instruction_document_assignment => valid_attributes}, valid_session
        response.should redirect_to(InstructionDocumentAssignment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instruction_document_assignment as @instruction_document_assignment" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionDocumentAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:instruction_document_assignment => { "instruction_id" => "invalid value" }}, valid_session
        assigns(:instruction_document_assignment).should be_a_new(InstructionDocumentAssignment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionDocumentAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:instruction_document_assignment => { "instruction_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instruction_document_assignment" do
        instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
        # Assuming there are no other instruction_document_assignments in the database, this
        # specifies that the InstructionDocumentAssignment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstructionDocumentAssignment.any_instance.should_receive(:update_attributes).with({ "instruction_id" => "1" })
        put :update, {:id => instruction_document_assignment.to_param, :instruction_document_assignment => { "instruction_id" => "1" }}, valid_session
      end

      it "assigns the requested instruction_document_assignment as @instruction_document_assignment" do
        instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
        put :update, {:id => instruction_document_assignment.to_param, :instruction_document_assignment => valid_attributes}, valid_session
        assigns(:instruction_document_assignment).should eq(instruction_document_assignment)
      end

      it "redirects to the instruction_document_assignment" do
        instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
        put :update, {:id => instruction_document_assignment.to_param, :instruction_document_assignment => valid_attributes}, valid_session
        response.should redirect_to(instruction_document_assignment)
      end
    end

    describe "with invalid params" do
      it "assigns the instruction_document_assignment as @instruction_document_assignment" do
        instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionDocumentAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => instruction_document_assignment.to_param, :instruction_document_assignment => { "instruction_id" => "invalid value" }}, valid_session
        assigns(:instruction_document_assignment).should eq(instruction_document_assignment)
      end

      it "re-renders the 'edit' template" do
        instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstructionDocumentAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => instruction_document_assignment.to_param, :instruction_document_assignment => { "instruction_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instruction_document_assignment" do
      instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
      expect {
        delete :destroy, {:id => instruction_document_assignment.to_param}, valid_session
      }.to change(InstructionDocumentAssignment, :count).by(-1)
    end

    it "redirects to the instruction_document_assignments list" do
      instruction_document_assignment = InstructionDocumentAssignment.create! valid_attributes
      delete :destroy, {:id => instruction_document_assignment.to_param}, valid_session
      response.should redirect_to(instruction_document_assignments_url)
    end
  end

end
