require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NoteProcessStepAssignmentsController do

  # This should return the minimal set of attributes required to create a valid
  # NoteProcessStepAssignment. As you add validations to NoteProcessStepAssignment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "note_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NoteProcessStepAssignmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all note_process_step_assignments as @note_process_step_assignments" do
      note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:note_process_step_assignments).should eq([note_process_step_assignment])
    end
  end

  describe "GET show" do
    it "assigns the requested note_process_step_assignment as @note_process_step_assignment" do
      note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
      get :show, {:id => note_process_step_assignment.to_param}, valid_session
      assigns(:note_process_step_assignment).should eq(note_process_step_assignment)
    end
  end

  describe "GET new" do
    it "assigns a new note_process_step_assignment as @note_process_step_assignment" do
      get :new, {}, valid_session
      assigns(:note_process_step_assignment).should be_a_new(NoteProcessStepAssignment)
    end
  end

  describe "GET edit" do
    it "assigns the requested note_process_step_assignment as @note_process_step_assignment" do
      note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
      get :edit, {:id => note_process_step_assignment.to_param}, valid_session
      assigns(:note_process_step_assignment).should eq(note_process_step_assignment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NoteProcessStepAssignment" do
        expect {
          post :create, {:note_process_step_assignment => valid_attributes}, valid_session
        }.to change(NoteProcessStepAssignment, :count).by(1)
      end

      it "assigns a newly created note_process_step_assignment as @note_process_step_assignment" do
        post :create, {:note_process_step_assignment => valid_attributes}, valid_session
        assigns(:note_process_step_assignment).should be_a(NoteProcessStepAssignment)
        assigns(:note_process_step_assignment).should be_persisted
      end

      it "redirects to the created note_process_step_assignment" do
        post :create, {:note_process_step_assignment => valid_attributes}, valid_session
        response.should redirect_to(NoteProcessStepAssignment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved note_process_step_assignment as @note_process_step_assignment" do
        # Trigger the behavior that occurs when invalid params are submitted
        NoteProcessStepAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:note_process_step_assignment => { "note_id" => "invalid value" }}, valid_session
        assigns(:note_process_step_assignment).should be_a_new(NoteProcessStepAssignment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NoteProcessStepAssignment.any_instance.stub(:save).and_return(false)
        post :create, {:note_process_step_assignment => { "note_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested note_process_step_assignment" do
        note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
        # Assuming there are no other note_process_step_assignments in the database, this
        # specifies that the NoteProcessStepAssignment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NoteProcessStepAssignment.any_instance.should_receive(:update_attributes).with({ "note_id" => "1" })
        put :update, {:id => note_process_step_assignment.to_param, :note_process_step_assignment => { "note_id" => "1" }}, valid_session
      end

      it "assigns the requested note_process_step_assignment as @note_process_step_assignment" do
        note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
        put :update, {:id => note_process_step_assignment.to_param, :note_process_step_assignment => valid_attributes}, valid_session
        assigns(:note_process_step_assignment).should eq(note_process_step_assignment)
      end

      it "redirects to the note_process_step_assignment" do
        note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
        put :update, {:id => note_process_step_assignment.to_param, :note_process_step_assignment => valid_attributes}, valid_session
        response.should redirect_to(note_process_step_assignment)
      end
    end

    describe "with invalid params" do
      it "assigns the note_process_step_assignment as @note_process_step_assignment" do
        note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NoteProcessStepAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => note_process_step_assignment.to_param, :note_process_step_assignment => { "note_id" => "invalid value" }}, valid_session
        assigns(:note_process_step_assignment).should eq(note_process_step_assignment)
      end

      it "re-renders the 'edit' template" do
        note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NoteProcessStepAssignment.any_instance.stub(:save).and_return(false)
        put :update, {:id => note_process_step_assignment.to_param, :note_process_step_assignment => { "note_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested note_process_step_assignment" do
      note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
      expect {
        delete :destroy, {:id => note_process_step_assignment.to_param}, valid_session
      }.to change(NoteProcessStepAssignment, :count).by(-1)
    end

    it "redirects to the note_process_step_assignments list" do
      note_process_step_assignment = NoteProcessStepAssignment.create! valid_attributes
      delete :destroy, {:id => note_process_step_assignment.to_param}, valid_session
      response.should redirect_to(note_process_step_assignments_url)
    end
  end

end
