require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProcessClassesController do

  # This should return the minimal set of attributes required to create a valid
  # ProcessClass. As you add validations to ProcessClass, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProcessClassesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all process_classes as @process_classes" do
      process_class = ProcessClass.create! valid_attributes
      get :index, {}, valid_session
      assigns(:process_classes).should eq([process_class])
    end
  end

  describe "GET show" do
    it "assigns the requested process_class as @process_class" do
      process_class = ProcessClass.create! valid_attributes
      get :show, {:id => process_class.to_param}, valid_session
      assigns(:process_class).should eq(process_class)
    end
  end

  describe "GET new" do
    it "assigns a new process_class as @process_class" do
      get :new, {}, valid_session
      assigns(:process_class).should be_a_new(ProcessClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested process_class as @process_class" do
      process_class = ProcessClass.create! valid_attributes
      get :edit, {:id => process_class.to_param}, valid_session
      assigns(:process_class).should eq(process_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProcessClass" do
        expect {
          post :create, {:process_class => valid_attributes}, valid_session
        }.to change(ProcessClass, :count).by(1)
      end

      it "assigns a newly created process_class as @process_class" do
        post :create, {:process_class => valid_attributes}, valid_session
        assigns(:process_class).should be_a(ProcessClass)
        assigns(:process_class).should be_persisted
      end

      it "redirects to the created process_class" do
        post :create, {:process_class => valid_attributes}, valid_session
        response.should redirect_to(ProcessClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved process_class as @process_class" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessClass.any_instance.stub(:save).and_return(false)
        post :create, {:process_class => {}}, valid_session
        assigns(:process_class).should be_a_new(ProcessClass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessClass.any_instance.stub(:save).and_return(false)
        post :create, {:process_class => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested process_class" do
        process_class = ProcessClass.create! valid_attributes
        # Assuming there are no other process_classes in the database, this
        # specifies that the ProcessClass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProcessClass.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => process_class.to_param, :process_class => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested process_class as @process_class" do
        process_class = ProcessClass.create! valid_attributes
        put :update, {:id => process_class.to_param, :process_class => valid_attributes}, valid_session
        assigns(:process_class).should eq(process_class)
      end

      it "redirects to the process_class" do
        process_class = ProcessClass.create! valid_attributes
        put :update, {:id => process_class.to_param, :process_class => valid_attributes}, valid_session
        response.should redirect_to(process_class)
      end
    end

    describe "with invalid params" do
      it "assigns the process_class as @process_class" do
        process_class = ProcessClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => process_class.to_param, :process_class => {}}, valid_session
        assigns(:process_class).should eq(process_class)
      end

      it "re-renders the 'edit' template" do
        process_class = ProcessClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => process_class.to_param, :process_class => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested process_class" do
      process_class = ProcessClass.create! valid_attributes
      expect {
        delete :destroy, {:id => process_class.to_param}, valid_session
      }.to change(ProcessClass, :count).by(-1)
    end

    it "redirects to the process_classes list" do
      process_class = ProcessClass.create! valid_attributes
      delete :destroy, {:id => process_class.to_param}, valid_session
      response.should redirect_to(process_classes_url)
    end
  end

end
