require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProcessIndicatorsController do

  # This should return the minimal set of attributes required to create a valid
  # ProcessIndicator. As you add validations to ProcessIndicator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProcessIndicatorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all process_indicators as @process_indicators" do
      process_indicator = ProcessIndicator.create! valid_attributes
      get :index, {}, valid_session
      assigns(:process_indicators).should eq([process_indicator])
    end
  end

  describe "GET show" do
    it "assigns the requested process_indicator as @process_indicator" do
      process_indicator = ProcessIndicator.create! valid_attributes
      get :show, {:id => process_indicator.to_param}, valid_session
      assigns(:process_indicator).should eq(process_indicator)
    end
  end

  describe "GET new" do
    it "assigns a new process_indicator as @process_indicator" do
      get :new, {}, valid_session
      assigns(:process_indicator).should be_a_new(ProcessIndicator)
    end
  end

  describe "GET edit" do
    it "assigns the requested process_indicator as @process_indicator" do
      process_indicator = ProcessIndicator.create! valid_attributes
      get :edit, {:id => process_indicator.to_param}, valid_session
      assigns(:process_indicator).should eq(process_indicator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProcessIndicator" do
        expect {
          post :create, {:process_indicator => valid_attributes}, valid_session
        }.to change(ProcessIndicator, :count).by(1)
      end

      it "assigns a newly created process_indicator as @process_indicator" do
        post :create, {:process_indicator => valid_attributes}, valid_session
        assigns(:process_indicator).should be_a(ProcessIndicator)
        assigns(:process_indicator).should be_persisted
      end

      it "redirects to the created process_indicator" do
        post :create, {:process_indicator => valid_attributes}, valid_session
        response.should redirect_to(ProcessIndicator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved process_indicator as @process_indicator" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessIndicator.any_instance.stub(:save).and_return(false)
        post :create, {:process_indicator => {}}, valid_session
        assigns(:process_indicator).should be_a_new(ProcessIndicator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessIndicator.any_instance.stub(:save).and_return(false)
        post :create, {:process_indicator => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested process_indicator" do
        process_indicator = ProcessIndicator.create! valid_attributes
        # Assuming there are no other process_indicators in the database, this
        # specifies that the ProcessIndicator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProcessIndicator.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => process_indicator.to_param, :process_indicator => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested process_indicator as @process_indicator" do
        process_indicator = ProcessIndicator.create! valid_attributes
        put :update, {:id => process_indicator.to_param, :process_indicator => valid_attributes}, valid_session
        assigns(:process_indicator).should eq(process_indicator)
      end

      it "redirects to the process_indicator" do
        process_indicator = ProcessIndicator.create! valid_attributes
        put :update, {:id => process_indicator.to_param, :process_indicator => valid_attributes}, valid_session
        response.should redirect_to(process_indicator)
      end
    end

    describe "with invalid params" do
      it "assigns the process_indicator as @process_indicator" do
        process_indicator = ProcessIndicator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessIndicator.any_instance.stub(:save).and_return(false)
        put :update, {:id => process_indicator.to_param, :process_indicator => {}}, valid_session
        assigns(:process_indicator).should eq(process_indicator)
      end

      it "re-renders the 'edit' template" do
        process_indicator = ProcessIndicator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProcessIndicator.any_instance.stub(:save).and_return(false)
        put :update, {:id => process_indicator.to_param, :process_indicator => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested process_indicator" do
      process_indicator = ProcessIndicator.create! valid_attributes
      expect {
        delete :destroy, {:id => process_indicator.to_param}, valid_session
      }.to change(ProcessIndicator, :count).by(-1)
    end

    it "redirects to the process_indicators list" do
      process_indicator = ProcessIndicator.create! valid_attributes
      delete :destroy, {:id => process_indicator.to_param}, valid_session
      response.should redirect_to(process_indicators_url)
    end
  end

end
